/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Thu Dec  5 14:06:00 2019. */

#include "thermalcam.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const uint32_t sony_MQTTConfig_port_default = 1883u;


const pb_field_t sony_Thermal_fields[5] = {
    PB_FIELD(  1, UINT64  , REQUIRED, STATIC  , FIRST, sony_Thermal, id, id, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, sony_Thermal, rows, id, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, sony_Thermal, cols, rows, 0),
    PB_FIELD(  4, INT32   , REPEATED, STATIC  , OTHER, sony_Thermal, data, cols, 0),
    PB_LAST_FIELD
};

const pb_field_t sony_MQTTConfig_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, sony_MQTTConfig, ip, ip, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, sony_MQTTConfig, port, ip, &sony_MQTTConfig_port_default),
    PB_FIELD(  3, STRING  , REQUIRED, STATIC  , OTHER, sony_MQTTConfig, uuid, port, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
#error Field descriptor for sony_Thermal.data is too large. Define PB_FIELD_16BIT to fix this.
#endif


/* @@protoc_insertion_point(eof) */
